<?php

use Illuminate\Database\Seeder;

class photoCollectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('photoCollection')->insert([
            [
                'pc_id'=>1,
                'photographer_id'=>1,
                'photo'=>'\Images\afternoon.jpg'
            ],
            [
                'pc_id'=>2,
                'photographer_id'=>1,
                'photo'=>'\Images\ants.jpg'
            ],
            [
                'pc_id'=>3,
                'photographer_id'=>1,
                'photo'=>'\Images\boat.jpg'
            ],
            [
                'pc_id'=>4,
                'photographer_id'=>2,
                'photo'=>'\Images\lion.jpg'
            ],
            [
                'pc_id'=>5,
                'photographer_id'=>2,
                'photo'=>'\Images\mushroom.jpg'
            ],
            [
                'pc_id'=>6,
                'photographer_id'=>2,
                'photo'=>'\Images\rose.jpg'
            ],
            [
                'pc_id'=>7,
                'photographer_id'=>2,
                'photo'=>'\Images\water.jpg'
            ],
            [
                'pc_id'=>8,
                'photographer_id'=>3,
                'photo'=>'\Images\afternoon.jpg'
            ],
            [
                'pc_id'=>9,
                'photographer_id'=>3,
                'photo'=>'\Images\ants.jpg'
            ],
            [
                'pc_id'=>10,
                'photographer_id'=>3,
                'photo'=>'\Images\boat.jpg'
            ],
            [
                'pc_id'=>11,
                'photographer_id'=>3,
                'photo'=>'\Images\lion.jpg'
            ],
            [
                'pc_id'=>12,
                'photographer_id'=>4,
                'photo'=>'\Images\mushroom.jpg'
            ],
            [
                'pc_id'=>13,
                'photographer_id'=>4,
                'photo'=>'\Images\rose.jpg'
            ],
            [
                'pc_id'=>14,
                'photographer_id'=>4,
                'photo'=>'\Images\water.jpg'
            ],
            [
                'pc_id'=>15,
                'photographer_id'=>5,
                'photo'=>'\Images\afternoon.jpg'
            ],
            [
                'pc_id'=>16,
                'photographer_id'=>5,
                'photo'=>'\Images\ants.jpg'
            ],
            [
                'pc_id'=>17,
                'photographer_id'=>5,
                'photo'=>'\Images\boat.jpg'
            ],
            [
                'pc_id'=>18,
                'photographer_id'=>6,
                'photo'=>'\Images\lion.jpg'
            ],
            [
                'pc_id'=>19,
                'photographer_id'=>6,
                'photo'=>'\Images\mushroom.jpg'
            ],
            [
                'pc_id'=>20,
                'photographer_id'=>6,
                'photo'=>'\Images\rose.jpg'
            ],
            [
                'pc_id'=>21,
                'photographer_id'=>6,
                'photo'=>'\Images\water.jpg'
            ],
            [
                'pc_id'=>22,
                'photographer_id'=>6,
                'photo'=>'\Images\afternoon.jpg'
            ],
            [
                'pc_id'=>23,
                'photographer_id'=>7,
                'photo'=>'\Images\ants.jpg'
            ],
            [
                'pc_id'=>24,
                'photographer_id'=>7,
                'photo'=>'\Images\boat.jpg'
            ],
            [
                'pc_id'=>25,
                'photographer_id'=>7,
                'photo'=>'\Images\lion.jpg'
            ],
            [
                'pc_id'=>26,
                'photographer_id'=>8,
                'photo'=>'\Images\mushroom.jpg'
            ],
            [
                'pc_id'=>27,
                'photographer_id'=>8,
                'photo'=>'\Images\rose.jpg'
            ],
            [
                'pc_id'=>28,
                'photographer_id'=>8,
                'photo'=>'\Images\water.jpg'
            ],
            
        ]);
    }
}
